'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {extractEmail,transformHeadersOnly}=require('../lib/email-engine');
const rawHeaders=`Delivered-To: inbox@gmail.com\r\nReceived: by gateway-a\r\n\tWed, 19 Aug 2026 03:01:30 -0700\r\nX-Received: remove-me\r\nARC-Seal: remove-me\r\nReturn-Path: <bounce@example.com>\r\nReceived: from gateway-b\r\n\tby mx.google.com\r\nReceived-SPF: pass\r\nAuthentication-Results: pass\r\nDKIM-Signature: remove-me\r\nX-Google-DKIM-Signature: remove-google-signature\r\nX-Gm-Message-State: remove-google-state\r\nX-Google-Smtp-Source: remove-google-source\r\nContent-Type: multipart/alternative; boundary=original-value\r\nDate: Wed, 19 Aug 2026 10:01:26 +0000\r\nFrom: Original Brand <email@example.com>\r\nMime-Version: 1.0\r\nMessage-ID: <abc@mailer.example>\r\nSubject: Original subject\r\n capsule\r\nList-Unsubscribe: <https://example.com/unsubscribe>\r\nTo: inbox@gmail.com\r\nX-Entity-ID: original-id`;
const params={headerFromName:'[P_FRNAME]',headerLanguageCode:'[6LAN]',headerReturnPath:'[P_RPATH]',headerSubject:'[S]',headerBoundary:'[BND]',headersAddSender:false};
test('Headers Only matches the supplied custom transformation',()=>{const output=transformHeadersOnly(rawHeaders,params);const expected=`Received: by gateway-a\r\n\tWed, 19 Aug 2026 03:01:30 -0700\r\nReceived: from gateway-b\r\n\tby mx.google.com\r\nContent-Type: multipart/related;boundary="[BND]";type="multipart/alternative"\r\nDate: [DATE]\r\nFrom: [P_FRNAME] <noreply.[6LAN]@[P_RPATH]>\r\nMime-Version: 1.0\r\nMessage-ID: <abc[EID]@mailer.example>\r\nSubject: [S]\r\n capsule\r\nList-Unsubscribe: <https://example.com/unsubscribe>\r\nTo: <[*to]>\r\nCc: [*to]\r\nX-Entity-ID: original-id`;assert.equal(output,expected)});
test('Headers Only strips the complete body',async()=>{const result=await extractEmail(Buffer.from(rawHeaders+'\r\n\r\nSECRET BODY'),'headers',params);assert.doesNotMatch(result.content.toString(),/SECRET BODY/)});
test('Headers Only Sender is off by default and optional',()=>{assert.doesNotMatch(transformHeadersOnly(rawHeaders,params),/^Sender:/m);assert.match(transformHeadersOnly(rawHeaders,{...params,headersAddSender:true}),/^Sender: noreply\.\[6LAN\]@\[P_RPATH\]$/m)});
