'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'public','styles.css'),'utf8');
test('progress bar selector matches the rendered UI',()=>{assert.match(html,/class="progress-rail"/);assert.match(app,/querySelector\('\.progress-rail'\)/);assert.doesNotMatch(app,/querySelector\('\.progress-track'\)/)});
test('browser assets use the current cache version',()=>{assert.match(html,/styles\.css\?v=7\.0/);assert.match(html,/app\.js\?v=7\.0/);assert.match(html,/v7\.0/)});
test('Headers Only controls are present and Sender starts unchecked',()=>{for(const id of ['headerFromName','headerLanguageCode','headerReturnPath','headerSubject','headerBoundary','headersAddSender'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/id="headersAddSender" type="checkbox">/);assert.doesNotMatch(html,/id="headersAddSender"[^>]*checked/)});
test('Clean Headers defaults, Received format, and mode locking are configured',()=>{const match=app.match(/const cleanDefaults=new Set\(\[([^\]]+)\]\)/);assert.ok(match);const defaults=[...match[1].matchAll(/'([^']+)'/g)].map(value=>value[1]);assert.deepEqual(defaults,['replaceDate','replaceTo','keepReceived','autoAddCc','keepReplyTo']);assert.match(app,/\['modernReceivedFormat','New Received Format'\]/);assert.ok(!defaults.includes('modernReceivedFormat'));assert.match(app,/function setModeLock\(value\)/);assert.match(app,/setModeLock\(true\);setBusy\(true,'Extraction in progress…'\)/)});
test('white theme is default and four themes persist',()=>{assert.match(html,/<html lang="en" data-theme="warm">/);for(const theme of ['warm','forest','ocean','midnight'])assert.match(html,new RegExp(`data-theme="${theme}"`));assert.equal((html.match(/class="theme-choice/g)||[]).length,4);assert.match(app,/localStorage\.setItem\('cmh9_theme_v6'/);assert.match(app,/localStorage\.getItem\('cmh9_theme_v6'/)});
test('latest theme layer uses only smooth linear gradients',()=>{const latest=css.split('/* V6.1 smooth professional gradients')[1];assert.ok(latest);assert.match(latest,/linear-gradient/g);assert.doesNotMatch(latest,/radial-gradient|repeating-linear-gradient/);assert.match(latest,/background-image:var\(--backdrop\)!important/)});
test('Telegram authentication gate is present',()=>{for(const id of ['authGate','appShell','telegramWidget','authPending','checkApprovalButton'])assert.match(html,new RegExp(`id="${id}"`));assert.match(app,/window\.onTelegramAuth/)});
test('footer displays only a clickable Telegram logo',()=>{assert.match(html,/href="https:\/\/t\.me\/ZakariaeSahli_cmh9"/);assert.match(html,/aria-label="Open Telegram"/);assert.doesNotMatch(html,/<span>@ZakariaeSahli_cmh9<\/span>/);assert.doesNotMatch(html,/>Terms</);assert.doesNotMatch(html,/>Privacy</);assert.doesNotMatch(html,/>Support</)});
