'use strict';
const crypto=require('crypto');
const LOGIN_MAX_AGE_SECONDS=10*60;
function safeEqualHex(left,right){if(!/^[a-f0-9]{64}$/i.test(String(left||''))||!/^[a-f0-9]{64}$/i.test(String(right||'')))return false;const a=Buffer.from(left,'hex'),b=Buffer.from(right,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sanitizeTelegramUser(input){return{id:String(input.id),first_name:String(input.first_name||'').slice(0,128),last_name:String(input.last_name||'').slice(0,128),username:String(input.username||'').slice(0,64),photo_url:String(input.photo_url||'').slice(0,512)}}
function verifyTelegramLogin(input,botToken,nowSeconds=Math.floor(Date.now()/1000)){if(!botToken||!input||!input.id||!input.auth_date||!input.hash)throw new Error('Invalid Telegram login data.');const authDate=Number(input.auth_date);if(!Number.isFinite(authDate)||Math.abs(nowSeconds-authDate)>LOGIN_MAX_AGE_SECONDS)throw new Error('Telegram login expired. Please try again.');const allowed=['auth_date','first_name','id','last_name','photo_url','username'];const check=allowed.filter(key=>input[key]!==undefined&&input[key]!==null&&String(input[key])!=='').sort().map(key=>`${key}=${input[key]}`).join('\n');const secret=crypto.createHash('sha256').update(botToken).digest();const expected=crypto.createHmac('sha256',secret).update(check).digest('hex');if(!safeEqualHex(expected,input.hash))throw new Error('Telegram signature verification failed.');return sanitizeTelegramUser(input)}
function createTelegramSessionToken(user,secret,ttlSeconds=30*24*60*60){if(!secret||secret.length<32)throw new Error('SESSION_SECRET must contain at least 32 characters.');const payload=Buffer.from(JSON.stringify({...sanitizeTelegramUser(user),exp:Math.floor(Date.now()/1000)+ttlSeconds})).toString('base64url');const signature=crypto.createHmac('sha256',secret).update(payload).digest('base64url');return `${payload}.${signature}`}
function openTelegramSessionToken(token,secret,nowSeconds=Math.floor(Date.now()/1000)){try{if(!secret||secret.length<32)return null;const [payload,signature,...extra]=String(token||'').split('.');if(!payload||!signature||extra.length)return null;const expected=crypto.createHmac('sha256',secret).update(payload).digest();const actual=Buffer.from(signature,'base64url');if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return null;const value=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));if(!value.id||!value.exp||Number(value.exp)<nowSeconds)return null;return sanitizeTelegramUser(value)}catch{return null}}
function isApprovedMember(member){return Boolean(member&&(['creator','administrator','member'].includes(member.status)||(member.status==='restricted'&&member.is_member===true)))}
module.exports={verifyTelegramLogin,createTelegramSessionToken,openTelegramSessionToken,isApprovedMember,sanitizeTelegramUser};
